app = "silent-dj-okjz-q"
primary_region = "jnb"

[build]
  # Use Dockerfile instead of buildpacks
  builder = "dockerfile"

[env]
  NODE_ENV = "production"

[experimental]
  cmd = ["node", "index.js"]
